### ISSUE TITLE
Allow null not implemented

### ISSUE THREAD

**Issue by tlechauve** [ChuckMac/ninja-forms-acf-field#4]
Hi,

Firstly thanks for this plugin.

I noticed that there was no implementation of "Allow null" feature. I suggest this code under the select tag

```
<?php if($field['allow_null'] == true) : ?>
   <option value="">-- <?php _e('None'); ?></option>
<?php endif ?>
```

Bye

**Comment by ChuckMac** [comment]
Thanks for the suggestion.  I have added this to version 3.1.
