### ISSUE TITLE
Not compatibile with Ninja Forms Three

### ISSUE THREAD

**Issue by JacobDB** [ChuckMac/ninja-forms-acf-field#5]
When trying to active this plugin with Ninja Forms Three active, I get the below error. The "Learn More" [links to here](https://ninjaforms.com/ninja-forms-three-extension-development-master-list/).

![image](https://cloud.githubusercontent.com/assets/1123997/17980562/78238328-6ac5-11e6-8518-3d80d7e5f664.png)

**Comment by hubsta** [comment]
#6 Will fix your issue.

**Comment by ChuckMac** [comment]
Fixed with #6
